version: '3'
services:
    nginx:
        image: nginx
        container_name: mn_nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - ipfs

    ipfs:
        image: swarmmasternodes/go-ipfs
        container_name: mn_ipfs
        ports:
            - '4001:4001'
            - '127.0.0.1:5001:5001'
            - '127.0.0.1:8080:8080'
            - '::1:5001:5001'
            - '::1:8080:8080'
        environment:
            LIBP2P_FORCE_PNET: 1
            IPFS_PROFILE: server
            SWARM_NODE: ipfs.swarm.fund
            SWARM_NODE_ID: QmdTXvVBcK3KoHpSy4zsnzzqzGkTVHTcsDYRhVjox36YxJ
        volumes:
            - './ipfs:/data/ipfs'
            - './ipfs/staging:/export'
